name: Build and Deploy Lholmberg

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
      - name: Build Site
        run: swift run Lholmberg
      - name: Deploy Content
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
          EXTERNAL_REPOSITORY: git@github.com:LHolmberg/lholmberg.github.io.git
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./Output
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          commitMessage: ${{ github.event.head_commit.message }}

